// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjNYPhbxOwS9_HSr3d56QGr7IGwdSkcE4',
    appId: '1:596848845488:android:4d9626ec261c03f8875175',
    messagingSenderId: '596848845488',
    projectId: 'teethkids-49f4b',
    storageBucket: 'teethkids-49f4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC84r-IA5PPwDiicNuIRS_kH2weH1zsu5o',
    appId: '1:596848845488:ios:1ed0493912be47e4875175',
    messagingSenderId: '596848845488',
    projectId: 'teethkids-49f4b',
    storageBucket: 'teethkids-49f4b.appspot.com',
    androidClientId: '596848845488-u8gvdnjh933tg6hnh0imcgeauusmn0p3.apps.googleusercontent.com',
    iosClientId: '596848845488-0nlhddfsto6frpsmhch3o2b9car1rvmf.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetoIntegrador3',
  );
}
